apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    app.kubernetes.io/part-of: casestudy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: demo
data:
  APP_ENV: "staging"
  LOG_LEVEL: "info"
